source "https://rubygems.org"

gem 'puma'
gem 'sinatra', require: 'sinatra/base'
gem 'rake'
gem 'sinatra-asset-pipeline', require: 'sinatra/asset_pipeline'
gem 'uglifier'
gem 'yui-compressor'
gem 'activemodel', '5.0.2', require: 'active_model'
gem 'pony'
gem 'goatmail'
gem 'padrino-helpers'

gem 'sass'
gem 'slim'

gem 'bourbon'
gem 'neat'
gem 'bitters'
