source 'https://rubygems.org'

# Padrino supports Ruby version 1.9 and later
# ruby '2.3.1'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'
gem 'puma'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'
gem 'padrino-sprockets', require: 'padrino/sprockets'
gem 'uglifier'
gem 'yui-compressor'
gem 'activemodel', '4.2.0', require: 'active_model'
gem 'goatmail', require: false

group :development do
  gem 'bourbon'
  gem 'neat'
  gem 'bitters'
  gem 'pry-padrino'
end

# Component requirements
gem 'sass'
gem 'slim'

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.13.2'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.13.2'
# end
